<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selectselect</name>
   <tag></tag>
   <elementGuidId>cce82c39-1fc2-454b-a163-8a076f0d6bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-hover.k-state-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='servingFacility']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-dropdown-wrap k-state-default k-state-hover k-state-focused</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selectselect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit94&quot;]/body[1]/div[@class=&quot;k-widget k-window soap-note&quot;]/div[@class=&quot;k-window-content k-content has-toolbar&quot;]/div[@class=&quot;content full-height&quot;]/div[@class=&quot;k-window-form-template editable-content encounter-Modal-class&quot;]/div[@class=&quot;col-sm-12 form form-horizontal encounter-stats&quot;]/div[@class=&quot;col-sm-12 no-padding&quot;]/div[@id=&quot;servingFacility&quot;]/div[@id=&quot;servingFacility&quot;]/span[@class=&quot;k-widget k-dropdown k-header form-control required-field&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AllSoapNoteTest/NewHRAFlows_Objects/iframe_SignOut_appCCM</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='servingFacility']/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Provider', &quot;'&quot;, 's Facility')])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[20]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/span/span</value>
   </webElementXpaths>
</WebElementEntity>
