import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import carecoordination_leftfilters.CR_RearrangingFilters_Runner



CucumberKW.runWithCucumberRunner(CR_RearrangingFilters_Runner.class)
