import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import based_on_patient_medical_record.UncheckAssessment_Runner

CucumberKW.runWithCucumberRunner(UncheckAssessment_Runner.class)
