import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import scheduleLeftFilters_NewCases.CR_ViewAppointments

CucumberKW.runWithCucumberRunner(CR_ViewAppointments.class)
