import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import all_features.CR_FromPreviousCarePlanFeature

CucumberKW.runWithCucumberRunner(CR_FromPreviousCarePlanFeature.class)