import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import all_features.CR_CareCoordinationFeature_CMStatus



CucumberKW.runWithCucumberRunner(CR_CareCoordinationFeature_CMStatus.class)