import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import superbill.CR_PDFView_ParticularPatient

CucumberKW.runWithCucumberRunner(CR_PDFView_ParticularPatient.class)
