import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import scheduleLeftFilters_NewCases.CR_AppointmentsLeftFiltersRetains

CucumberKW.runWithCucumberRunner(CR_AppointmentsLeftFiltersRetains.class)
