import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import scheduleLeftFilters_NewCases.CR_LeftFilters_Status

CucumberKW.runWithCucumberRunner(CR_LeftFilters_Status.class)
