import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import carecoordination_leftfilters.CR_OpenPatientByMRN_Runner

CucumberKW.runWithCucumberRunner(CR_OpenPatientByMRN_Runner.class)
